name: Node Continuous Integration

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Yarn packages (client UI)
        run: |
          cd client
          yarn install
      #   - name: Testing solution (client UI)
      #     run: |
      #       cd client
      #       yarn test
      - name: Build solution (client UI)
        run: |
          cd client
          yarn build
